fixing linting

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,7 +10,7 @@ on:
       - main
 
 jobs:
-  lint:
+   lint:
     runs-on: ubuntu-latest
     steps:
       - name: Check out code
@@ -19,16 +19,16 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: '3.12'
+          python-version: '3.8'
 
-      - name: Install Python dependencies
+      - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install flake8  # Install Python linter
           pip install -r requirements.txt
 
-      - name: Run Python Linter
-        run: flake8 .  
+      - name: Run Linter
+        run: |
+          flake8 . || { echo "Linting failed"; exit 1; }
 
       - name: Set up Node.js
         uses: actions/setup-node@v2
